collections:
  - name: HomemadeCake
    start_id: 1
    end_id: 2

yandex_cloud:
  access_key_id: "YCAJEEy-gpApVtzVYl6HdB-hC"
  secret_access_key: "YCNyCzlGNBz1yP05vPM0SBB70ba4QB94T_iGbZlo"
  bucket_name: "ai-ru"
  gifts_folder: "gifts"
  json_folder: "json_data"
