collections:
  - name: HomemadeCake
    start_id: 1
    end_id: 2

yandex_cloud:
  access_key_id: "YCAJEKw4bew3ESTnRhzxndLO7"
  secret_access_key: "YCOdAiH7-Xws76s9rUg-Q_r5tmavYJzAnxrlns3f"
  bucket_name: "ai-ru"
  gifts_folder: "gifts"
  main_folder: ""  # Оставляем пустым для загрузки в корень
  json_folder: "json_data"
